# Generated by Django 5.2.8 on 2025-11-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='matricule',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
