# Generated by Django 5.2.8 on 2025-11-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='media',
            field=models.ImageField(upload_to='media_actualite/'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='media',
            field=models.ImageField(upload_to='media_evenement/'),
        ),
        migrations.AlterField(
            model_name='ressourceislamique',
            name='fichier',
            field=models.ImageField(upload_to='media_ressourceIslamique/'),
        ),
    ]
